version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: oritool-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hameedgoovi123
      POSTGRES_DB: oritool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oritool-network

volumes:
  postgres_data:

networks:
  oritool-network:
    driver: bridge
